# Playing with Matrices and Tensors

In [1]:
import numpy as np

In [2]:
arr = [[1, 2], [3, 4]]
print(type(arr))
arr

<class 'list'>


[[1, 2], [3, 4]]

In [3]:
numpy_array = np.array(arr)
print(type(numpy_array))
numpy_array

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [5]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [8]:
np.random.rand(2, 2)

array([[0.31323531, 0.37886514],
       [0.91505712, 0.51847344]])

In [9]:
torch.rand(2, 2)


 0.8869  0.2651
 0.8458  0.6157
[torch.FloatTensor of size 2x2]

# Matrix Reproducibility

In [10]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
np.random.seed(0)
np.random.rand(3, 3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [12]:
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [13]:
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

# Numpy to Torch

In [14]:
np_array = np.ones((2, 2))
print(type(np_array))
np_array

<class 'numpy.ndarray'>


array([[1., 1.],
       [1., 1.]])

In [15]:
torch_tensor = torch.from_numpy(np_array)
print(type(torch_tensor))
torch_tensor

<class 'torch.DoubleTensor'>



 1  1
 1  1
[torch.DoubleTensor of size 2x2]

```
1. int64 - Long Tensor
2. int32 - Integer Tensor
3. uint8 - Byte Tensor
4. float64 - Double Tensor
5. float32 - Float Tensor
6. double - Double Tensor
```

In [21]:
new_array_double = np.ones((2, 2), dtype = np.double)
torch.from_numpy(new_array_double)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [22]:
new_array_int = np.ones((2, 2), dtype = np.int32)
torch.from_numpy(new_array_int)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [23]:
new_array_byte = np.ones((2, 2), dtype = np.uint8)
torch.from_numpy(new_array_byte)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

# Torch to Numpy

In [24]:
torch_tensor = torch.ones(2, 2)
torch_tensor


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [25]:
numpy_array = torch_tensor.numpy()
numpy_array

array([[1., 1.],
       [1., 1.]], dtype=float32)

# Tensor Mean

In [26]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [27]:
a.mean()

5.5

In [28]:
a.mean(dim = 0)


 5.5000
[torch.FloatTensor of size 1]

In [29]:
b = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
b.size()

torch.Size([2, 10])

In [30]:
b.mean()

5.5

In [31]:
# b.mean(dim = 0)
b.mean(dim = 1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

In [32]:
c = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
c.std(dim = 1)


 3.0277
 3.0277
[torch.FloatTensor of size 2]