In [1]:
import numpy as np

In [2]:
# Input Array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

In [3]:
# Output Array for X
y=np.array([[1],[1],[0]])

In [4]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [5]:
# 5000 Iterations/Epochs for the forward Net
epoch=5000

# Learning Rate
lr=0.1

# Number of features in data set
inputlayer_neurons = X.shape[1] 

# Hidden Layers
hiddenlayer_neurons = 3

# One Output Layer
output_neurons = 1

In [6]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)
print(output)


[[0.89400263]
 [0.90352448]
 [0.88844773]]


In [7]:
# Backpropagation
E = y-output
slope_output_layer = derivatives_sigmoid(output)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
d_output = E * slope_output_layer
Error_at_hidden_layer = d_output.dot(wout.T)
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
wout += hiddenlayer_activations.T.dot(d_output) *lr
bout += np.sum(d_output, axis=0,keepdims=True) *lr
wh += X.T.dot(d_hiddenlayer) *lr
bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 [[1]
 [1]
 [0]] 

predicted :
 [[0.89400263]
 [0.90352448]
 [0.88844773]]
